# Generated by Django 6.0.4 on 2026-05-01 03:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biological_name', models.CharField(max_length=200)),
                ('local_name', models.CharField(blank=True, max_length=200)),
                ('english_name', models.CharField(max_length=200)),
                ('family_name', models.CharField(blank=True, max_length=200)),
                ('care_notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='plants/')),
                ('planted_on', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('removed', 'Removed')], default='active', max_length=20)),
                ('removed_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-planted_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CareLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('care_type', models.CharField(choices=[('watering', 'Watering'), ('fertilizer', 'Fertilizer'), ('pruning', 'Pruning'), ('repotting', 'Repotting'), ('other', 'Other')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('performed_on', models.DateField(default=django.utils.timezone.localdate)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_logs', to='plants.plant')),
            ],
            options={
                'ordering': ['-performed_on', '-created_at'],
            },
        ),
    ]
