# Generated by Django 6.0.4 on 2026-05-01 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
